# Generated by Django 3.2 on 2022-06-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making_queryset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
