# Generated by Django 3.2 on 2022-06-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making_queryset', '0002_alter_blog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
